drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  URL TEXT NOT NULL,
  description TEXT,
  rating INTEGER NOT NULL
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, URL, description, rating)
values
    ('yahoo', 'https://www.yahoo.com/', 'search engine', 3),
    ('wikipedia', 'https://www.wikipedia.com/', 'encyclopedia',5),
    ('bestbuy', 'https://www.bestbuy.com/', 'electronics store',3),
    ('reddit', 'https://www.reddit.com/','threads',5),
    ('google', 'https://www.google.com/', 'biggest search engine',4),
    ('twitter', 'https://www.twitter.com/', 'social media craze',3),
    ('medium', 'https://www.medium.com/', 'tech news',4),
    ('apple', 'https://www.apple.com/','product page for apple', 1),
    ('firefox', 'https://www.mozilla.org/', 'best browser',5),
    ('steam', 'https://www.steam.com/', 'game site',2);
